[tool.poetry]
name = "wombo"
version = "0.3.0"
description = ""
authors = ["Алексей Баев <baev@cumproject.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.27.2"
pydantic = "^2.9.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
